[pytest]
python_files = test_*.py
python_functions = test_*
python_classes = Test*
testpaths = tests

markers =
    smoke: Smoke test suite
    sanity: Sanity test suite
    regression: Regression suite
    booking: Booking service tests
    auth: Authentication tests
    driver: Driver service tests